version: '3.6'
services:
  web:
    image: 'jenkins/jenkins'
    container_name: jenkins
    restart: always
    ports:
      - '50000:50000'
      - '8080:8080'
    volumes:
      - '/home/jezhang/data/jenkins:/var/jenkins_home'
