version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ce'
    container_name: gitlab
    restart: always
    hostname: '192.168.219.129'
    ports:
      - '8090:80'
      - '8443:443'
      - '8022:22'
    volumes:
      - '/home/jezhang/data/gitlab/config:/etc/gitlab'
      - '/home/jezhang/data/gitlab/logs:/var/log/gitlab'
      - '/home/jezhang/data/gitlab/data:/var/opt/gitlab'
    shm_size: '256m'
