version: "3"

networks:
  rustdesk-net:
    external: false

services:
  hbbs:
    container_name: hbbs
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    image: rustdesk/rustdesk-server
    command: hbbs -r 192.168.1.198:21117
    volumes:
      - /root/data/rustdesk/hbbs:/root
    networks:
      - rustdesk-net
    depends_on:
      - hbbr
    restart: unless-stopped
    environment:
      - http_proxy=http://192.168.1.132:7890
      - https_proxy=http://192.168.1.132:7890

  hbbr:
    container_name: hbbr
    ports:
      - 21117:21117
      - 21119:21119
    image: rustdesk/rustdesk-server
    command: hbbr
    volumes:
      - /root/data/rustdesk/hbbr:/root
    networks:
      - rustdesk-net
    restart: unless-stopped
    environment:
      - http_proxy=http://192.168.1.132:7890
      - https_proxy=http://192.168.1.132:7890

