version: "3"

services:
  server:
    #image: linuxserver/code-server
    image: gitpod/openvscode-server
    container_name: code-server
    #environment:
      #  - DOCKER_USER=$USER
      #- PUID=1000
      #- PGID=1000
      #- PROXY_DOMAIN=code-server.my.domain
      #- DEFAULT_WORKSPACE=/config/workspace
    restart: always
    volumes:
      #- /root/data/code-server/config:/config
      - /root/data/code-server/workspace:/home/workspace
    ports:
      - "8443:3000"
