version: '2'

services:
  mongodb:
    #image: docker.io/bitnami/mongodb:5.0
    image: docker.io/bitnami/mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGODB_ROOT_USER=jezhang
      - MONGODB_ROOT_PASSWORD=password123
    volumes:
      - '/root/mnt/mongodb-data:/bitnami/mongodb'

volumes:
  mongodb_data:
    driver: local
